service: stackdrift-detection
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  region: ${opt:region}
  memorySize: 1024
  timeout: 900
  role: ${self:custom.roles.${opt:stage}}
custom:
  roles:
    dev:
    uat:
    prod:
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns: dispatch
  cronHandler:
    handler: handler.run
    events:
      - schedule: cron(10 9 ? * mon *)
